### ISSUE TITLE
LSLAutobids TODO

### ISSUE THREAD

**Issue by ReboreExplore** [s-ccs/LSLAutoBIDS#7]
- [ ] Handle the memory spike problem with the BrainVision Format
- [ ] Handle negative voltage issue - only with some recordings
- [ ] Writing tests with a sample recording
- [ ] Triple push issue to DaRUS (dataverse)

**Comment by behinger** [comment]
- EDF is fine, we don't particulary care about BrainVision - I thnk both are BIDS compatible
- negative voltage issue? what was that?
- [ ] fix the TSV/CSV issue that dissallows upload CSV/TSV via dataverse https://github.com/datalad/datalad-dataverse/issues/307 somehow...

**Comment by ReboreExplore** [comment]
@behinger the negative onset issue is this one : https://github.com/bids-standard/pybv/issues/110
It is not yet resolved.

**Comment by ReboreExplore** [comment]
Yes EDF fixes it now. I am marking the TODO as done!

**Comment by ReboreExplore** [comment]
Closing this as these are mostly solved and redundant to the new issues.
